import json
import os
import re

SESSION_DIR = r"C:\Users\83734\Desktop\opentrace\test-commit-repository\.opentrace\session_20260630_172421_en"

# Ordered by length descending for accurate replacement
REPLACEMENTS = [
    # Phrases (longest first)
    ("该脚本不包含针对帖子内容、发布时间、用户、相似度或历史案例的新增筛选、匹配、排序或统计规则；相关分析判断已由前序报告提供，本节点只负责最终整合和一致性确认。", "This script does not include new filtering, matching, sorting, or statistical rules for post content, posting time, users, similarity, or historical cases; relevant analytical judgments have been provided by previous reports, and this node is only responsible for final integration and consistency verification."),
    ("最终关系视图不是重新筛选原始事件，而是基于当前会话目录中已经记录的全部分析实体、活动和关联关系生成，因此结果反映的是前序各节点累计形成的完整分析上下文。", "The final relationship view is not a re-filtering of raw events, but is generated based on all analysis entities, activities, and association relationships already recorded in the current session directory; therefore, the result reflects the complete analysis context accumulated from previous nodes."),
    ("以目标异常帖子的时间为基准，计算每条指令任务与目标帖子的时间差，并区分目标帖子之前和之后发生的指令任务，用于判断哪些实例可能是异常发布前的相关尝试。", "Using the target anomalous post time as a baseline, calculate the time difference between each instruction task and the target post, and distinguish instruction tasks occurring before and after the target post, to determine which instances may be relevant attempts before the anomalous publication."),
    ("目标人员匹配采用文本包含规则：将事件内容整体转为文本后，与标准化后的目标人员名称进行不区分大小写的包含匹配，用于判断某个事件是否与该目标人员相关。", "Target personnel matching uses text containment rules: after converting the entire event content to text, perform case-insensitive containment matching with the standardized target personnel name to determine whether an event is related to that target personnel."),
    ("该脚本不重新计算相似度、不筛选帖子、不排序候选事件，也不改变异常事件链的分析结论，只负责将已完成的相似实例分析结果纳入最终视图并进行一致性检查。", "This script does not recalculate similarity, filter posts, sort candidate events, or change the analysis conclusions of the anomalous event chain; it is only responsible for incorporating completed similar-instance analysis results into the final view and performing consistency checks."),
    ("最终验证结果中保留可视化内容长度、验证是否通过、验证错误和最终调查报告路径，用于判断最终视图是否成功生成以及调查记录是否存在结构性问题。", "The final verification result retains visualization content length, pass/fail status, verification errors, and final investigation report path, used to determine whether the final view was successfully generated and whether there are structural problems in the investigation record."),
    ("完整性验证使用当前会话目录中的分析产物作为检查对象，输出是否通过验证以及错误列表；若存在错误，则说明最终分析结果仍有缺失或不一致之处。", "Integrity verification uses the analysis artifacts in the current session directory as the inspection object, outputting whether verification passed and an error list; if errors exist, it indicates that the final analysis result still has missing or inconsistent parts."),
    ("最终关系视图不设置额外筛选条件，纳入所选会话目录下的全部已记录分析关系，用于展示从前序调查步骤到最终报告和验证结果的整体关联结构。", "The final relationship view does not set additional filtering conditions, incorporating all recorded analysis relationships under the selected session directory, used to display the overall association structure from previous investigation steps to the final report and verification results."),
    ("作为异常帖子的唯一判定对象，不在本步骤重新筛选或比对其他帖子；异常事件的时间、事件编号、论坛和事件类型均直接来自该目标帖子记录。", "As the sole judgment object for the anomalous post, this step does not re-filter or compare other posts; the anomalous event time, event ID, forum, and event type all come directly from the target post record."),
    ("最终视图的关系判断基于两个来源共同形成：补充相似实例分析报告用于补充历史相似行为线索，上一版可视化用于保留既有异常帖子事件链。", "The relationship judgment of the final view is formed jointly from two sources: the supplemental similar-instance analysis report is used to supplement historical similar-behavior clues, and the previous version of the visualization is used to retain the existing anomalous post event chain."),
    ("内容来源文件的创建事件按事件时间顺序查找；如果存在多个匹配创建事件，采用时间上最早被匹配到的创建事件作为该来源文件的创建证据。", "Creation events for content-source files are searched in chronological order; if multiple matching creation events exist, the earliest matched creation event in time is adopted as the creation evidence for that source file."),
    ("对三次异常帖提取到的文件创建者进行去重统计，得到异常内容来源文件涉及的唯一创建者列表，用于比较三次异常是否来自相同或不同来源。", "Deduplicate and count the file creators extracted from the three anomalous posts to obtain the list of unique creators involved in the anomalous content source files, used to compare whether the three anomalies come from the same or different sources."),
    ("当三次异常帖子中至少存在一个空内容或乱码内容时，形成结论：异常发帖存在内容质量问题，说明技术上的发布不一定等同于有效信息泄露。", "When at least one of the three anomalous posts has empty or garbled content, the conclusion is formed: anomalous posting has content quality issues, indicating that technical publication does not necessarily equate to effective information leakage."),
    ("基于当前会话中的全部已记录分析步骤和产物关系，生成一张全局关系图，用于展示调查过程中输入、输出、分析活动之间的整体连接结构。", "Based on all recorded analysis steps and product relationships in the current session, generate a global relationship diagram used to display the overall connection structure among inputs, outputs, and analysis activities during the investigation."),
    ("每次外泄分别统计后续访问事件数量、帖子浏览事件数量、源文件删除状态和帖子删除状态；其中后续访问和浏览事件在结果中最多保留前", "For each leakage, separately count the number of subsequent access events, post browsing events, source file deletion status, and post deletion status; among them, subsequent access and browsing events retain at most the first"),
    ("当标准会话目录不存在时，使用带“备份”后缀的同一会话目录作为替代数据来源；这一规则会影响最终被可视化和验证的记录范围。", "When the standard session directory does not exist, use the same session directory with a \"backup\" suffix as the alternative data source; this rule affects the scope of records finally visualized and verified."),
    ("后缀的文件名主干都作为匹配关键词，用于在原始事件中识别与该来源文件相关的事件；匹配方式为事件完整文本中包含任一关键词。", "The filename stem with the suffix is used as the matching keyword to identify events related to this source file in raw events; the matching method is that the complete event text contains any keyword."),
    ("验证逻辑以所选会话目录为检查对象，判断该调查会话是否满足完整性和一致性要求，并输出布尔型通过状态以及对应错误列表。", "The verification logic takes the selected session directory as the inspection object, determines whether the investigation session meets integrity and consistency requirements, and outputs a Boolean pass status and the corresponding error list."),
    ("，但实际发布内容为空，因此没有真实信息泄露；其意义更可能是模拟外泄、系统测试、信号传递、掩盖行为或内部政治操作。", ", but the actual published content is empty, so there is no real information leakage; its significance is more likely simulated leakage, system testing, signal transmission, cover-up behavior, or internal political maneuvering."),
    ("输出结果反映的是前序分析过程之间的依赖关系，例如最终报告如何作为输入、可视化结果如何由该报告及已有分析记录形成。", "The output results reflect the dependency relationships among previous analysis processes, such as how the final report serves as input and how visualization results are formed from that report and existing analysis records."),
    ("将当前分析会话中已记录的处理步骤、输入输出和相互依赖关系整理成可视化说明，用于展示异常帖子分析结果的形成链路。", "Organize the recorded processing steps, inputs/outputs, and interdependencies in the current analysis session into a visualization description, used to display the formation chain of the anomalous post analysis results."),
    ("按帖子级别统计三类内容状态的数量，包括空内容数量、乱码内容数量和正常内容数量，并以异常帖子总数作为统计分母。", "At the post level, count the quantities of three types of content statuses, including empty content count, garbled content count, and normal content count, using the total number of anomalous posts as the statistical denominator."),
    ("中的创建事件判断源文件来源；创建者取创建事件中的第一个参与者，创建时间和文件大小提示取该创建事件的对应字段。", "The creation event in is used to judge the source file origin; the creator is taken as the first participant in the creation event, and the creation time and file size hint are taken from the corresponding fields of that creation event."),
    ("脚本明确建立最终分析报告与验证结果之间的派生关系，表示验证结果用于确认基于该报告形成的最终分析会话是否可用。", "The script explicitly establishes the derivation relationship between the final analysis report and the verification result, indicating that the verification result is used to confirm whether the final analysis session formed based on that report is usable."),
    ("，但报告未发现该文件的创建事件或创建者；因此其具体语义无法由该报告确认，只能确认其来源文件名和异常发帖行为。", ", but the report did not find a creation event or creator for this file; therefore, its specific semantics cannot be confirmed by the report, and only its source file name and anomalous posting behavior can be confirmed."),
    ("将最终报告、最终可视化结果和校验结果建立明确的来源关系，用于说明最终图示和校验结论均来自修正后的调查报告。", "Establish clear provenance relationships among the final report, final visualization result, and verification result, used to explain that the final diagram and verification conclusions both come from the revised investigation report."),
    ("指令传播链只保留发生在异常帖发布时间之前或同一时刻的事件，避免将发帖之后的事件误认为导致发帖的上游原因。", "The instruction propagation chain only retains events occurring before or at the same time as the anomalous post publication time, avoiding misidentifying events after posting as upstream causes of the post."),
    ("删除生命周期、临近发帖的任务传递链，以及与该内容源相关的事件类型统计。该数据是小型中间分析结果，共汇总", "deletion lifecycle, task transmission chain near posting, and event type statistics related to this content source. This data is a small intermediate analysis result, summarizing a total of"),
    ("对全系统异常帖子进行分组聚合，统计每个异常发帖人的异常发帖数量，并保存其异常帖子明细、职位和部门信息。", "Group and aggregate all anomalous posts in the system, count the number of anomalous posts per anomalous poster, and save their anomalous post details, position, and department information."),
    ("作为异常发布前的直接任务链证据，将其中的事件时间、事件编号、事件类型、参与者和详情整理为发布前因果链。", "As direct task chain evidence before the anomalous publication, organize the event time, event ID, event type, participants, and details within it into a pre-publication causal chain."),
    ("对修正后的最终调查结果进行整体关系图生成与一致性校验，用于确认分析链条是否完整、可解释且无结构性错误。", "Perform overall relationship diagram generation and consistency verification on the revised final investigation results, used to confirm whether the analysis chain is complete, explainable, and free of structural errors."),
    ("将上一版关系图作为对照输入，并记录其文件大小，用于确认最终关系图是在已有可视化结果基础上的刷新版本。", "Use the previous version of the relationship diagram as a control input and record its file size, used to confirm that the final relationship diagram is a refreshed version based on existing visualization results."),
    ("围绕已定位异常帖子的内容来源文件，追溯其文件生命周期、临近任务链、关键人员交互和异常前上游任务证据。", "Around the content source file of the located anomalous post, trace its file lifecycle, nearby task chain, key personnel interactions, and upstream task evidence before the anomaly."),
    ("对当前会话的分析记录进行一致性校验，判断会话中的分析步骤、输入输出产物和关联关系是否满足完整性要求。", "Perform consistency verification on the analysis records of the current session, determining whether the analysis steps, input/output products, and association relationships in the session meet integrity requirements."),
    ("判断相似指令任务是否发生在目标异常帖子之前，从而支持这些行为属于异常帖子前的历史背景或前置传播实例。", "Determine whether similar instruction tasks occurred before the target anomalous post, thereby supporting that these behaviors belong to the historical background or pre-dissemination instances before the anomalous post."),
    ("数据结构，不改变事件字段、嵌套关系、时间信息、参与者信息或内容信息，因此该步骤不会引入新的分析判断。", "data structure, without changing event fields, nested relationships, time information, participant information, or content information; therefore, this step will not introduce new analytical judgments."),
    ("通过检查三次异常帖是否都能匹配到来源文件创建事件，判断异常内容是否都可以追溯到明确的文件生成来源。", "By checking whether all three anomalous posts can match source file creation events, determine whether anomalous content can all be traced back to explicit file generation sources."),
    ("将最终报告和上一版关系图共同作为最终关系图的来源依据，使最终输出同时保留分析结论和既有关系结构。", "Use both the final report and the previous version of the relationship diagram as the source basis for the final relationship diagram, so that the final output retains both analysis conclusions and existing relationship structures."),
    ("汇总三次数据外泄验证结果与相关人员调查结果，判断外泄是否成功并评估关键人员的参与程度和风险等级。", "Summarize the three data leakage verification results and related personnel investigation results, determine whether the leakage was successful, and evaluate the participation level and risk level of key personnel."),
    ("以前序最终报告作为核心依据，提取其中记录的异常帖子事件标识，用于标注最终关系图所对应的目标事件。", "Use the previous final report as the core basis, extract the anomalous post event identifiers recorded therein, and use them to label the target events corresponding to the final relationship diagram."),
    ("以及来源文件名主干作为关联条件；事件文本中包含任一关键人员或来源文件名主干即视为与异常链条相关。", "and the source file name stem as association conditions; if the event text contains any key personnel or source file name stem, it is considered related to the anomalous chain."),
    ("以当前会话作为分析范围，只展示该会话内已经记录的分析步骤和数据关系，避免混入其他会话的处理结果。", "Use the current session as the analysis scope, only displaying analysis steps and data relationships already recorded within this session, avoiding mixing in processing results from other sessions."),
    ("验证已识别的多次异常发帖是否构成成功的数据外泄，并评估源文件删除、帖子留存、后续访问和浏览情况。", "Verify whether the identified multiple anomalous posts constitute successful data leakage, and evaluate source file deletion, post retention, subsequent access, and browsing."),
    ("使用最终关系图的文本长度作为输出规模指标，用于说明最终可视化内容是否成功生成并具备非空结果。", "Use the text length of the final relationship diagram as the output scale indicator, used to explain whether the final visualization content was successfully generated and has non-empty results."),
    ("对当前会话的完整记录进行整体检查，判断分析记录是否有效，并保留所有检查错误作为质量验证结果。", "Perform an overall check of the complete records of the current session, determine whether the analysis records are valid, and retain all inspection errors as quality verification results."),
    ("在近邻关键事件中，只保留能够反映任务传递、发帖检查、实际发帖、文件读取和文件删除的事件类型：", "Among nearby key events, only retain event types that can reflect task transmission, posting checks, actual posting, file reading, and file deletion:"),
    ("人员相关事件采用文本包含匹配规则识别：将事件整体内容转为小写文本后，判断其中是否包含目标人员", "Personnel-related events are identified using text containment matching rules: after converting the entire event content to lowercase text, determine whether it contains the target personnel"),
    ("；文件是否删除、帖子是否仍存在、是否有后续访问只作为成功状态的补充证据，不改变该成功判定。", "; whether the file was deleted, whether the post still exists, and whether there was subsequent access serve only as supplementary evidence for success status, not changing the success determination."),
    ("的事件数量，统计每个内容来源文件在发帖前关联到的下级任务指令数量，作为指令传播强度的指标。", "The number of events, counting the number of subordinate task instructions associated with each content source file before posting, serves as an indicator of instruction propagation intensity."),
    ("使用最终报告中的异常帖子事件标识作为目标事件标注，用于说明本次可视化对应的核心分析对象。", "Use the anomalous post event identifiers in the final report as target event labels, used to explain the core analysis object corresponding to this visualization."),
    ("三次异常发帖的上下文、内容来源文件和相关指令事件，提炼这些异常发帖之间的共同模式与差异。", "The context of the three anomalous posts, content source files, and related instruction events, extracting the common patterns and differences among these anomalous posts."),
    ("最终结论依赖前序问题评估结果和系统变更建议结果，其中推荐干预方案直接采用前序变更建议中的", "The final conclusion relies on previous problem evaluation results and system change recommendation results, among which the recommended intervention plan directly adopts those from previous change recommendations"),
    ("等于指令文件名，或任务详情文本中包含该指令文件名；该规则用于确认任务确实要求读取或处理", "equals the instruction file name, or the task detail text contains that instruction file name; this rule is used to confirm that the task indeed requires reading or processing"),
    ("最终结论由四类证据共同支撑：目标异常帖子、内容来源文件、发布前任务链、发布后删除行为。", "The final conclusion is jointly supported by four types of evidence: target anomalous post, content source file, pre-publication task chain, and post-publication deletion behavior."),
    ("完整分析完成后，基于已有分析成果刷新最终关系视图，并检查当前分析会话结果是否完整一致。", "After the complete analysis is finished, refresh the final relationship view based on existing analysis results, and check whether the current analysis session results are complete and consistent."),
    ("条相关事件，可作为排查历史重复行为的证据范围；报告片段未给出其他已确认异常帖子的数量。", "related events, which can serve as the evidence scope for investigating historical repeated behaviors; the report fragment does not give the number of other confirmed anomalous posts."),
    ("指向该文件；同时将帖子内容为空作为异常特征，用于推断问题更可能来自系统处理或配置缺陷。", "points to this file; at the same time, taking empty post content as an anomalous feature is used to infer that the problem is more likely from system processing or configuration defects."),
    ("将上一版数据流可视化结果作为对照输入，使最终视图继承此前已经确认的事件链和系统关系。", "Use the previous version of the data flow visualization result as a control input, so that the final view inherits the previously confirmed event chain and system relationships."),
    ("是否包含该关键词；若存在匹配事件，则判定该外泄的源文件已被删除，即存在证据清理行为。", "whether it contains this keyword; if a matching event exists, it is determined that the source file of this leakage has been deleted, that is, evidence cleanup behavior exists."),
    ("在补充相似实例分析完成后，生成最终的数据流关系视图，并检查当前分析会话的结果完整性。", "After the supplemental similar-instance analysis is completed, generate the final data flow relationship view and check the result integrity of the current analysis session."),
    ("脚本明确建立最终分析报告与最终可视化结果之间的派生关系，表示最终视图的主要依据来自", "The script explicitly establishes the derivation relationship between the final analysis report and the final visualization result, indicating that the main basis for the final view comes from"),
    ("、是否成功外泄、是否删除帖子、后续文件删除访问、浏览量以及总体对比结论。数据表明", ", whether leakage was successful, whether the post was deleted, subsequent file deletion access, browsing volume, and overall comparison conclusion. Data indicates"),
    ("事件子集执行目标异常帖子定位后的中间分析结果，包含目标时间、筛选计数、唯一匹配的", "Intermediate analysis result after executing target anomalous post localization on the event subset, containing target time, filter count, uniquely matched"),
    ("对完整调查结果进行最终关系视图生成，并验证该调查会话中的分析记录是否完整、有效。", "Generate the final relationship view for the complete investigation results, and verify whether the analysis records in this investigation session are complete and valid."),
    ("次历史异常实例的共性模式，以及推荐的系统干预方案。数据表明异常并非数据外泄，而是", "common patterns of historical anomalous instances, and recommended system intervention plans. Data indicates that the anomaly is not data leakage, but rather"),
    ("将补充相似实例分析报告作为最终视图更新的主要依据，其中明确保留异常发帖相关人员为", "Use the supplemental similar-instance analysis report as the main basis for final view updates, explicitly retaining anomalous posting-related personnel as"),
    ("将已追溯出的异常帖子、来源文件、任务链和删除行为汇总为面向结论的最终分析说明。", "Summarize the traced anomalous posts, source files, task chains, and deletion behaviors into a conclusion-oriented final analysis description."),
    ("作为此前相似性与数据流分析视图的参考输入，用于将早期分析关系纳入最终视图背景。", "As a reference input for previous similarity and data flow analysis views, used to incorporate early analysis relationships into the final view background."),
    ("的完整链条；其他目标人员虽然存在相似指令传播，但没有形成相同的异常发帖结果。", "complete chain; other target personnel, although having similar instruction propagation, did not form the same anomalous posting results."),
    ("、事件类型、时间戳、可读时间、参与方、详情和原始事件内容，便于后续继续分析。", ", event type, timestamp, readable time, participants, details, and raw event content, facilitating subsequent continued analysis."),
    ("帖子的根因、推荐干预点、备选干预点、预期效果和附加收益展开。核心结论是建议在", "root causes of posts, recommended intervention points, alternative intervention points, expected effects, and additional benefits. The core conclusion recommends intervention at"),
    ("字段存在且非空；该字段被视为帖子内容来自外部来源或被引用生成的关键异常证据。", "field exists and is non-empty; this field is regarded as key anomalous evidence that the post content comes from an external source or is generated by citation."),
    ("按指令任务的来源人员统计任务发起次数，并按目标人员统计任务接收次数，用于判断", "Count task initiation times by the source personnel of instruction tasks, and count task reception times by target personnel, used to determine"),
    ("指令任务及其后续结果的比较结果，判断历史上是否存在类似实例，并解释为什么只有", "comparison results of instruction tasks and their subsequent results, determining whether similar instances exist historically, and explaining why only"),
    ("作为内容来源线索，并结合异常模式分析中的对应发帖时间作为该次外泄的基准时间。", "as the content source clue, and combining the corresponding posting time in the anomaly pattern analysis as the baseline time for this leakage."),
    ("不对事件进行筛选、排序、聚合或匹配处理，完整保留原始数据中的全部事件记录。", "No filtering, sorting, aggregation, or matching processing is performed on events; all event records in the raw data are completely retained."),
    ("一人，说明问题集中在该用户或其代理链路上，而不是广泛扩散的系统性发帖故障。", "one person, indicating that the problem is concentrated on this user or their agent chain, rather than a widely diffused systematic posting failure."),
    ("进行计数汇总，用于概括该来源文件涉及哪些类型的系统行为以及各类型出现次数。", "perform counting and summarization, used to summarize what types of system behaviors this source file involves and how many times each type occurs."),
    ("等任务源内容直接进入发帖流程。该位置覆盖目标异常帖子的直接来源，并可拦截", "and other task source content directly enters the posting process. This location covers the direct source of the target anomalous post and can intercept"),
    ("发布以及源文件和指令文件删除，用于解释其异常发帖与其他未发帖实例的差异。", "publication and source file and instruction file deletion, used to explain the differences between its anomalous posting and other non-posting instances."),
    ("秒内完成，将整体事件定性为跨部门、有组织的数据外泄，而非单次偶然故障。", "completed within seconds, characterizing the overall event as a cross-departmental, organized data leakage rather than a single accidental failure."),
    ("次异常发布均由该执行点完成，且所有异常的直接表现都是空内容帖子被发布。", "anomalous publications were all completed by this execution point, and the direct manifestation of all anomalies was that empty-content posts were published."),
    ("个相关事件；但当前报告未给出其他异常帖子的明确匹配数量或历史重复结论。", "related events; however, the current report does not give the explicit match count of other anomalous posts or historical repetition conclusions."),
    ("三次异常发帖的共同模式、来源文件创建者、相关指令数量和详细上下文事件。", "common patterns of the three anomalous posts, source file creators, related instruction counts, and detailed context events."),
    ("的调查分析结果，涵盖两人的人员画像、活动类型统计、敏感文件访问次数、三次疑似外泄事件的指令来源与内容来源、行为模式、怀疑等级和后续调查建议。该数据集是小型中间分析结果，用于识别", "investigation analysis results, covering personnel profiles of two individuals, activity type statistics, sensitive file access counts, instruction sources and content sources of three suspected leakage events, behavior patterns, suspicion levels, and subsequent investigation recommendations. This dataset is a small intermediate analysis result, used to identify"),
    ("个核心问题的回答状态、证据节点、事件链摘要、问题重构、根因假设以及后续分析缺口与建议。该数据集是小型中间分析结果，用于评估异常帖子事件链追踪、系统概览、内容来源、历史重复实例和干预建议的完成情况。", "core questions' answer status, evidence nodes, event chain summaries, problem reconstructions, root cause hypotheses, and subsequent analysis gaps and recommendations. This dataset is a small intermediate analysis result, used to evaluate the completion status of anomalous post event chain tracing, system overview, content sources, historical repetition instances, and intervention recommendations."),
    ("该数据集为小型中间验证结果，当前验证状态为通过，错误数量为", "This dataset is a small intermediate verification result; the current verification status is passed, and the error count is"),
    ("该记录显示验证通过且错误数量为", "This record shows that verification passed and the error count is"),
    ("该记录显示验证通过且无错误。", "This record shows that verification passed with no errors."),
    ("该结果显示调查已完成并回答", "This result shows that the investigation is completed and answered"),
    ("当前结果显示验证通过且错误数量为", "The current result shows that verification passed and the error count is"),
    ("该记录表明", "This record indicates"),
    ("可视化内容基于已有的步骤关系、输入数据、输出结果和派生关系生成，不再对原始事件进行新的筛选、匹配、排序或统计。", "Visualization content is generated based on existing step relationships, input data, output results, and derivation relationships, and no longer performs new filtering, matching, sorting, or statistics on raw events."),
    ("最终结论依赖前序问题评估结果和系统变更建议结果，其中推荐干预方案直接采用前序变更建议中的", "The final conclusion relies on previous problem evaluation results and system change recommendation results, among which the recommended intervention plan directly adopts those from previous change recommendations"),
]

WORD_REPLACEMENTS = [
    ("原始数据完整加载", "Raw data fully loaded"),
    ("数据加载", "Data loading"),
    ("原始数据", "raw data"),
    ("加载", "loading"),
    ("当前会话元数据概览", "Current session metadata overview"),
    ("当前会话", "current session"),
    ("会话元数据", "session metadata"),
    ("元数据", "metadata"),
    ("会话", "session"),
    ("当前", "current"),
    ("包含", "Contains"),
    ("包括", "including"),
    ("工作目录", "working directory"),
    ("路径", "path"),
    ("该文件", "This file"),
    ("用于", "is used for"),
    ("定位", "locating"),
    ("本次", "this"),
    ("任务", "task"),
    ("运行环境", "runtime environment"),
    ("而非", "rather than"),
    ("原始", "raw"),
    ("事件", "event"),
    ("数据", "data"),
    ("条记录", "records"),
    ("涵盖", "covering"),
    ("邮件访问与发送", "email access and sending"),
    ("会议提议", "meeting proposals"),
    ("文件访问", "file access"),
    ("子任务派发", "subtask dispatch"),
    ("发帖", "posting"),
    ("检查", "checking"),
    ("门禁", "access control"),
    ("房间进入", "room entry"),
    ("等行为", "and other behaviors"),
    ("可用于", "can be used for"),
    ("追踪", "tracking"),
    ("人员", "personnel"),
    ("系统服务", "system services"),
    ("之间", "between"),
    ("时序交互", "temporal interactions"),
    ("异常传播链", "anomaly propagation chains"),
    ("字段数量", "field count"),
    ("存在字段", "existing fields"),
    ("概览", "overview"),
    ("智能体", "agent"),
    ("多智能体", "multi-agent"),
    ("系统的", "system"),
    ("活动", "activity"),
    ("日志", "log"),
    ("中过滤", "filtered from"),
    ("相关事件", "related events"),
    ("在", "in"),
    ("从", "from"),
    ("追溯", "trace"),
    ("基于目标帖子", "based on target post"),
    ("基于", "based on"),
    ("目标帖子", "target post"),
    ("追溯文件生命周期和任务链", "trace file lifecycle and task chain"),
    ("证据链生成最终分析报告", "evidence chain generates final analysis report"),
    ("数据生成数据血缘可视化", "data generates data lineage visualization"),
    ("刷新完整", "refresh complete"),
    ("可视化并验证", "visualize and verify"),
    ("会话完整性", "session integrity"),
    ("查找所有类似", "find all similar"),
    ("指令实例", "instruction instances"),
    ("类似异常发帖行为及其他未发帖实例", "similar anomalous posting behavior and other non-posting instances"),
    ("比较每条指令后的短窗口行为", "compare short-window behavior after each instruction"),
    ("比较类似", "compare similar"),
    ("指令实例的后续", "subsequent of instruction instances"),
    ("发布结果", "publish results"),
    ("生成历史类似实例与", "generate historical similar instances and"),
    ("唯一成功发帖原因的补充报告", "supplemental report on the cause of the only successful post"),
    ("补充相似实例分析后刷新", "refresh after supplemental similar instance analysis"),
    ("去重统计", "deduplication statistics"),
    ("按帖子级别", "by post level"),
    ("帖子级别", "post level"),
    ("三类", "three types"),
    ("内容状态", "content status"),
    ("空内容", "empty content"),
    ("乱码内容", "garbled content"),
    ("正常内容", "normal content"),
    ("统计分母", "statistical denominator"),
    ("中的创建事件", "creation event in"),
    ("判断源文件来源", "judge source file origin"),
    ("创建者", "creator"),
    ("取", "take"),
    ("创建时间", "creation time"),
    ("文件大小提示", "file size hint"),
    ("对应字段", "corresponding fields"),
    ("脚本明确建立", "script explicitly establishes"),
    ("最终分析报告", "final analysis report"),
    ("之间的派生关系", "derivation relationship between"),
    ("表示", "indicating"),
    ("确认", "confirm"),
    ("形成", "form"),
    ("最终分析会话", "final analysis session"),
    ("是否可用", "whether usable"),
    ("但报告未发现", "but report did not find"),
    ("该文件的", "this file's"),
    ("创建事件", "creation event"),
    ("因此", "therefore"),
    ("其具体语义", "its specific semantics"),
    ("无法由该报告确认", "cannot be confirmed by this report"),
    ("只能确认", "can only confirm"),
    ("其来源文件名", "its source file name"),
    ("异常发帖行为", "anomalous posting behavior"),
    ("将最终报告", "use final report"),
    ("最终可视化结果", "final visualization result"),
    ("建立明确的来源关系", "establish clear provenance relationships"),
    ("说明", "explain"),
    ("最终图示", "final diagram"),
    ("校验结论", "verification conclusions"),
    ("均来自", "both come from"),
    ("修正后的调查报告", "revised investigation report"),
    ("指令传播链", "instruction propagation chain"),
    ("只保留", "only retain"),
    ("发生在", "occurring at"),
    ("异常帖发布时间", "anomalous post publication time"),
    ("之前", "before"),
    ("同一时刻", "same time"),
    ("避免", "avoid"),
    ("将", "taking"),
    ("发帖之后", "after posting"),
    ("误认为", "misidentifying as"),
    ("导致发帖的上游原因", "upstream cause of posting"),
    ("、验证是否通过", ", whether verification passed"),
    ("错误列表", "error list"),
    ("可视化文件路径", "visualization file path"),
    ("会话文件路径", "session file path"),
    ("修订报告路径", "revised report path"),
    ("作为异常发布前的直接任务链证据", "as direct task chain evidence before anomalous publication"),
    ("将其中的", "organize its"),
    ("事件时间", "event time"),
    ("事件编号", "event ID"),
    ("整理为", "into"),
    ("发布前因果链", "pre-publication causal chain"),
    ("对修正后的", "on revised"),
    ("最终调查结果", "final investigation results"),
    ("整体关系图生成", "overall relationship diagram generation"),
    ("一致性校验", "consistency verification"),
    ("用于确认", "used to confirm"),
    ("分析链条", "analysis chain"),
    ("是否完整", "whether complete"),
    ("可解释", "explainable"),
    ("且无结构性错误", "and free of structural errors"),
    ("将上一版关系图", "use previous version of relationship diagram"),
    ("作为对照输入", "as control input"),
    ("并记录其文件大小", "and record its file size"),
    ("用于确认最终关系图", "used to confirm final relationship diagram"),
    ("是在已有可视化结果基础上的刷新版本", "is a refreshed version based on existing visualization results"),
    ("围绕", "around"),
    ("已定位", "located"),
    ("异常帖子", "anomalous post"),
    ("内容来源文件", "content source file"),
    ("追溯其", "trace its"),
    ("文件生命周期", "file lifecycle"),
    ("临近任务链", "nearby task chain"),
    ("关键人员交互", "key personnel interactions"),
    ("异常前上游任务证据", "upstream task evidence before anomaly"),
    ("对当前会话", "on current session"),
    ("分析记录", "analysis records"),
    ("进行一致性校验", "perform consistency verification"),
    ("判断", "determine"),
    ("会话中的", "in session"),
    ("分析步骤", "analysis steps"),
    ("输入输出产物", "input/output products"),
    ("关联关系", "association relationships"),
    ("是否满足完整性要求", "whether integrity requirements are met"),
    ("判断相似指令任务", "determine similar instruction tasks"),
    ("是否发生在", "whether occurred at"),
    ("目标异常帖子", "target anomalous post"),
    ("从而支持", "thereby supporting"),
    ("这些行为", "these behaviors"),
    ("属于", "belong to"),
    ("异常帖子前的历史背景", "historical background before anomalous post"),
    ("前置传播实例", "pre-dissemination instances"),
    ("不改变", "without changing"),
    ("事件字段", "event fields"),
    ("嵌套关系", "nested relationships"),
    ("时间信息", "time information"),
    ("参与者信息", "participant information"),
    ("内容信息", "content information"),
    ("因此该步骤", "therefore this step"),
    ("不会引入新的分析判断", "will not introduce new analytical judgments"),
    ("通过检查", "by checking"),
    ("三次", "three"),
    ("异常帖", "anomalous posts"),
    ("是否都能匹配到", "whether all can match"),
    ("来源文件创建事件", "source file creation events"),
    ("异常内容", "anomalous content"),
    ("是否都可以追溯到", "whether all can be traced back to"),
    ("明确的文件生成来源", "explicit file generation sources"),
    ("将最终报告和上一版关系图", "use both final report and previous relationship diagram"),
    ("共同作为", "jointly as"),
    ("最终关系图的来源依据", "source basis for final relationship diagram"),
    ("使最终输出", "so that final output"),
    ("同时保留", "simultaneously retains"),
    ("分析结论", "analysis conclusions"),
    ("既有关系结构", "existing relationship structures"),
    ("汇总", "summarize"),
    ("三次数据外泄验证结果", "three data leakage verification results"),
    ("相关人员调查结果", "related personnel investigation results"),
    ("判断外泄是否成功", "determine whether leakage was successful"),
    ("评估", "evaluate"),
    ("关键人员", "key personnel"),
    ("参与程度", "participation level"),
    ("风险等级", "risk level"),
    ("以前序最终报告", "use previous final report"),
    ("作为核心依据", "as core basis"),
    ("提取其中记录的", "extract recorded"),
    ("异常帖子事件标识", "anomalous post event identifiers"),
    ("标注", "label"),
    ("最终关系图", "final relationship diagram"),
    ("所对应的目标事件", "corresponding target events"),
    ("以及", "and"),
    ("来源文件名主干", "source file name stem"),
    ("作为关联条件", "as association conditions"),
    ("事件文本中", "in event text"),
    ("包含任一", "contains any"),
    ("即视为", "is considered"),
    ("与异常链条相关", "related to anomalous chain"),
    ("以当前会话", "use current session"),
    ("作为分析范围", "as analysis scope"),
    ("只展示", "only display"),
    ("该会话内", "within this session"),
    ("已经记录的", "already recorded"),
    ("分析步骤", "analysis steps"),
    ("数据关系", "data relationships"),
    ("避免混入", "avoid mixing in"),
    ("其他会话", "other sessions"),
    ("处理结果", "processing results"),
    ("验证已识别的", "verify identified"),
    ("多次", "multiple"),
    ("异常发帖", "anomalous posts"),
    ("是否构成", "whether constitute"),
    ("成功的数据外泄", "successful data leakage"),
    ("源文件删除", "source file deletion"),
    ("帖子留存", "post retention"),
    ("后续访问", "subsequent access"),
    ("浏览情况", "browsing"),
    ("使用最终关系图的文本长度", "use final relationship diagram text length"),
    ("作为输出规模指标", "as output scale indicator"),
    ("用于说明", "used to explain"),
    ("最终可视化内容", "final visualization content"),
    ("是否成功生成", "whether successfully generated"),
    ("并具备非空结果", "and has non-empty results"),
    ("完整记录", "complete records"),
    ("整体检查", "overall check"),
    ("分析记录是否有效", "whether analysis records are valid"),
    ("保留所有检查错误", "retain all inspection errors"),
    ("作为质量验证结果", "as quality verification results"),
    ("在近邻关键事件中", "among nearby key events"),
    ("只保留能够反映", "only retain those reflecting"),
    ("任务传递", "task transmission"),
    ("发帖检查", "posting checks"),
    ("实际发帖", "actual posting"),
    ("文件读取", "file reading"),
    ("文件删除", "file deletion"),
    ("的事件类型", "event types"),
    ("人员相关事件", "personnel-related events"),
    ("采用文本包含匹配规则识别", "identified using text containment matching rules"),
    ("将事件整体内容转为小写文本后", "after converting entire event content to lowercase"),
    ("判断其中是否包含", "determine whether it contains"),
    ("目标人员", "target personnel"),
    ("文件是否删除", "whether file was deleted"),
    ("帖子是否仍存在", "whether post still exists"),
    ("是否有后续访问", "whether there was subsequent access"),
    ("只作为成功状态的补充证据", "serve only as supplementary evidence for success status"),
    ("不改变该成功判定", "not changing success determination"),
    ("统计每个", "count each"),
    ("内容来源文件", "content source file"),
    ("在发帖前", "before posting"),
    ("关联到的", "associated"),
    ("下级任务指令数量", "subordinate task instruction count"),
    ("作为指令传播强度的指标", "as indicator of instruction propagation intensity"),
    ("使用最终报告中的", "use in final report"),
    ("作为目标事件标注", "as target event labels"),
    ("本次可视化", "this visualization"),
    ("对应的核心分析对象", "corresponding core analysis object"),
    ("上下文", "context"),
    ("相关指令事件", "related instruction events"),
    ("提炼", "extract"),
    ("这些", "these"),
    ("之间的", "among"),
    ("共同模式", "common patterns"),
    ("差异", "differences"),
    ("最终结论", "final conclusion"),
    ("依赖", "relies on"),
    ("前序", "previous"),
    ("问题评估结果", "problem evaluation results"),
    ("系统变更建议结果", "system change recommendation results"),
    ("其中", "among which"),
    ("推荐干预方案", "recommended intervention plan"),
    ("直接采用", "directly adopts"),
    ("前序变更建议中的", "from previous change recommendations"),
    ("等于", "equals"),
    ("指令文件名", "instruction file name"),
    ("或任务详情文本中包含", "or task detail text contains"),
    ("该指令文件名", "that instruction file name"),
    ("该规则用于确认", "this rule confirms"),
    ("任务确实要求", "task indeed requires"),
    ("读取或处理", "reading or processing"),
    ("由四类证据共同支撑", "jointly supported by four types of evidence"),
    ("发布前任务链", "pre-publication task chain"),
    ("发布后删除行为", "post-publication deletion behavior"),
    ("完整分析完成后", "after complete analysis"),
    ("基于已有分析成果", "based on existing analysis results"),
    ("刷新最终关系视图", "refresh final relationship view"),
    ("检查当前分析会话结果", "check current analysis session results"),
    ("是否完整一致", "whether complete and consistent"),
    ("条相关事件", "related events"),
    ("可作为", "can serve as"),
    ("排查", "investigate"),
    ("历史重复行为", "historical repeated behaviors"),
    ("证据范围", "evidence scope"),
    ("报告片段", "report fragment"),
    ("未给出", "does not give"),
    ("其他", "other"),
    ("已确认", "confirmed"),
    ("异常帖子的", "anomalous posts'"),
    ("明确匹配数量", "explicit match count"),
    ("历史重复结论", "historical repetition conclusions"),
    ("指向该文件", "points to this file"),
    ("同时将帖子内容为空", "simultaneously taking empty post content"),
    ("作为异常特征", "as anomalous feature"),
    ("用于推断", "used to infer"),
    ("问题更可能来自", "problem more likely from"),
    ("系统处理", "system processing"),
    ("配置缺陷", "configuration defects"),
    ("将上一版数据流可视化结果", "use previous data flow visualization result"),
    ("使最终视图继承", "so final view inherits"),
    ("此前已经确认的", "previously confirmed"),
    ("事件链", "event chain"),
    ("系统关系", "system relationships"),
    ("是否包含该关键词", "whether contains this keyword"),
    ("若存在匹配事件", "if matching event exists"),
    ("则判定", "then determine"),
    ("该外泄的源文件", "this leakage's source file"),
    ("已被删除", "has been deleted"),
    ("即存在证据清理行为", "that is evidence cleanup behavior exists"),
    ("在补充相似实例分析完成后", "after supplemental similar instance analysis"),
    ("生成最终的数据流关系视图", "generate final data flow relationship view"),
    ("检查当前分析会话", "check current analysis session"),
    ("结果完整性", "result integrity"),
    ("脚本明确建立", "script explicitly establishes"),
    ("最终分析报告", "final analysis report"),
    ("表示最终视图", "indicating final view"),
    ("主要依据", "main basis"),
    ("来自", "comes from"),
    ("是否成功外泄", "whether leakage successful"),
    ("是否删除帖子", "whether post deleted"),
    ("后续文件删除访问", "subsequent file deletion access"),
    ("浏览量", "browsing volume"),
    ("总体对比结论", "overall comparison conclusion"),
    ("数据表明", "data indicates"),
    ("事件子集", "event subset"),
    ("执行", "execute"),
    ("目标异常帖子定位", "target anomalous post localization"),
    ("后的", "after"),
    ("中间分析结果", "intermediate analysis result"),
    ("包含", "containing"),
    ("目标时间", "target time"),
    ("筛选计数", "filter count"),
    ("唯一匹配的", "uniquely matched"),
    ("对完整调查结果", "on complete investigation results"),
    ("进行最终关系视图生成", "generate final relationship view"),
    ("验证该调查会话", "verify this investigation session"),
    ("是否完整有效", "whether complete and valid"),
    ("次历史异常实例", "historical anomalous instances"),
    ("共性模式", "common patterns"),
    ("推荐的系统干预方案", "recommended system intervention plans"),
    ("异常并非数据外泄", "anomaly is not data leakage"),
    ("而是", "but rather"),
    ("将补充相似实例分析报告", "use supplemental similar instance analysis report"),
    ("作为最终视图更新的主要依据", "as main basis for final view update"),
    ("其中明确保留", "explicitly retaining"),
    ("异常发帖相关人员", "anomalous posting related personnel"),
    ("为", "as"),
    ("将已追溯出的", "summarize traced"),
    ("异常帖子", "anomalous posts"),
    ("来源文件", "source files"),
    ("任务链", "task chains"),
    ("删除行为", "deletion behaviors"),
    ("汇总为", "summarize into"),
    ("面向结论的", "conclusion-oriented"),
    ("最终分析说明", "final analysis description"),
    ("作为此前", "as previous"),
    ("相似性", "similarity"),
    ("数据流分析视图", "data flow analysis view"),
    ("参考输入", "reference input"),
    ("用于将早期分析关系", "used to incorporate early analysis relationships"),
    ("纳入最终视图背景", "into final view background"),
    ("的完整链条", "complete chain"),
    ("其他目标人员", "other target personnel"),
    ("虽然存在", "although having"),
    ("相似指令传播", "similar instruction propagation"),
    ("但没有形成", "but did not form"),
    ("相同的", "same"),
    ("异常发帖结果", "anomalous posting results"),
    ("时间戳", "timestamp"),
    ("可读时间", "readable time"),
    ("参与方", "participants"),
    ("详情", "details"),
    ("原始事件内容", "raw event content"),
    ("便于后续继续分析", "facilitating subsequent analysis"),
    ("根因", "root causes"),
    ("推荐干预点", "recommended intervention points"),
    ("备选干预点", "alternative intervention points"),
    ("预期效果", "expected effects"),
    ("附加收益", "additional benefits"),
    ("展开", "expand"),
    ("核心结论", "core conclusion"),
    ("建议是", "recommend"),
    ("字段存在", "field exists"),
    ("且非空", "and is non-empty"),
    ("该字段", "this field"),
    ("被视为", "is regarded as"),
    ("帖子内容", "post content"),
    ("来自外部来源", "from external source"),
    ("或被引用生成", "or generated by citation"),
    ("关键异常证据", "key anomalous evidence"),
    ("按指令任务", "by instruction task"),
    ("来源人员", "source personnel"),
    ("统计任务发起次数", "count task initiation times"),
    ("并按目标人员", "and by target personnel"),
    ("统计任务接收次数", "count task reception times"),
    ("用于判断", "used to determine"),
    ("指令任务及其后续结果", "instruction tasks and subsequent results"),
    ("比较结果", "comparison results"),
    ("判断历史上", "determine historically"),
    ("是否存在类似实例", "whether similar instances exist"),
    ("并解释", "and explain"),
    ("为什么只有", "why only"),
    ("作为内容来源线索", "as content source clue"),
    ("并结合", "and combining"),
    ("异常模式分析", "anomaly pattern analysis"),
    ("对应发帖时间", "corresponding posting time"),
    ("作为该次外泄的基准时间", "as baseline time for this leakage"),
    ("不对事件进行", "no event"),
    ("筛选", "filtering"),
    ("排序", "sorting"),
    ("聚合", "aggregation"),
    ("匹配处理", "matching processing"),
    ("完整保留", "completely retain"),
    ("原始数据中的", "in raw data"),
    ("全部事件记录", "all event records"),
    ("一人", "one person"),
    ("说明问题集中在", "indicating problem concentrated on"),
    ("该用户", "this user"),
    ("或其代理链路上", "or their agent chain"),
    ("而不是", "rather than"),
    ("广泛扩散的", "widely diffused"),
    ("系统性发帖故障", "systematic posting failure"),
    ("计数汇总", "counting summarization"),
    ("概括", "summarize"),
    ("该来源文件", "this source file"),
    ("涉及", "involves"),
    ("哪些类型", "what types"),
    ("系统行为", "system behaviors"),
    ("各类型出现次数", "occurrence count of each type"),
    ("等任务源内容", "and other task source content"),
    ("直接进入", "directly enter"),
    ("发帖流程", "posting process"),
    ("该位置", "this location"),
    ("覆盖", "covers"),
    ("目标异常帖子的", "target anomalous post's"),
    ("直接来源", "direct source"),
    ("并可拦截", "and can intercept"),
    ("发布", "publication"),
    ("源文件", "source file"),
    ("指令文件", "instruction file"),
    ("删除", "deletion"),
    ("用于解释", "used to explain"),
    ("其异常发帖", "its anomalous posting"),
    ("与其他未发帖实例", "with other non-posting instances"),
    ("差异", "differences"),
    ("秒内完成", "completed within seconds"),
    ("将整体事件定性为", "characterize overall event as"),
    ("跨部门", "cross-departmental"),
    ("有组织的", "organized"),
    ("数据外泄", "data leakage"),
    ("单次偶然故障", "single accidental failure"),
    ("次异常发布", "anomalous publications"),
    ("均由该执行点完成", "all completed by this execution point"),
    ("且所有异常的直接表现", "and direct manifestation of all anomalies"),
    ("都是空内容帖子被发布", "was empty-content posts published"),
    ("个相关事件", "related events"),
    ("但当前报告", "but current report"),
    ("未给出", "does not give"),
    ("其他异常帖子的", "other anomalous posts'"),
    ("或历史重复结论", "or historical repetition conclusions"),
    ("共同模式", "common patterns"),
    ("来源文件创建者", "source file creators"),
    ("相关指令数量", "related instruction counts"),
    ("详细上下文事件", "detailed context events"),
    ("的调查分析结果", "investigation analysis results"),
    ("两人", "two individuals"),
    ("人员画像", "personnel profiles"),
    ("活动类型统计", "activity type statistics"),
    ("敏感文件访问次数", "sensitive file access counts"),
    ("三次疑似外泄事件", "three suspected leakage events"),
    ("指令来源", "instruction sources"),
    ("内容来源", "content sources"),
    ("行为模式", "behavior patterns"),
    ("怀疑等级", "suspicion levels"),
    ("后续调查建议", "subsequent investigation recommendations"),
    ("该数据集是小型中间分析结果", "this dataset is a small intermediate analysis result"),
    ("用于识别", "used to identify"),
    ("个核心问题", "core questions"),
    ("回答状态", "answer status"),
    ("证据节点", "evidence nodes"),
    ("事件链摘要", "event chain summaries"),
    ("问题重构", "problem reconstructions"),
    ("根因假设", "root cause hypotheses"),
    ("后续分析缺口", "subsequent analysis gaps"),
    ("建议", "recommendations"),
    ("用于评估", "used to evaluate"),
    ("异常帖子事件链追踪", "anomalous post event chain tracing"),
    ("系统概览", "system overview"),
    ("历史重复实例", "historical repetition instances"),
    ("干预建议", "intervention recommendations"),
    ("完成情况", "completion status"),
    (" Tenant Thread ", " Tenant Thread "),
    ("多智能体", "multi-agent"),
    ("智能体", "agent"),
    ("数量", "count"),
    ("总数", "total count"),
    ("已回答问题", "answered questions"),
    ("调查是否完成", "investigation complete"),
    ("分析", "analysis"),
    ("可视化", "visualization"),
    ("报告", "report"),
    ("验证", "verification"),
    ("结果", "result"),
    ("输入", "input"),
    ("输出", "output"),
    ("步骤", "step"),
    ("节点", "node"),
    ("关系", "relationship"),
    ("实体", "entity"),
    ("活动", "activity"),
    ("代理", "agent"),
    ("来源", "source"),
    ("派生", "derived"),
    ("生成", "generate"),
    ("刷新", "refresh"),
    ("修正", "revise"),
    ("补充", "supplement"),
    ("相似", "similar"),
    ("异常", "anomalous"),
    ("帖子", "post"),
    ("文件", "file"),
    ("指令", "instruction"),
    ("任务", "task"),
    ("事件", "event"),
    ("人员", "personnel"),
    ("用户", "user"),
    ("调查", "investigation"),
    ("记录", "record"),
    ("数据", "data"),
    ("信息", "information"),
    ("内容", "content"),
    ("时间", "time"),
    ("字段", "field"),
    ("状态", "status"),
    ("类型", "type"),
    ("详情", "details"),
    ("描述", "description"),
    ("名称", "name"),
    ("路径", "path"),
    ("目录", "directory"),
    ("文本", "text"),
    ("长度", "length"),
    ("大小", "size"),
    ("错误", "error"),
    ("通过", "pass"),
    ("失败", "fail"),
    ("成功", "success"),
    ("完整", "complete"),
    ("有效", "valid"),
    ("缺失", "missing"),
    ("不一致", "inconsistent"),
    ("原始", "raw"),
    ("最终", "final"),
    ("中间", "intermediate"),
    ("全局", "global"),
    ("整体", "overall"),
    ("局部", "local"),
    ("全部", "all"),
    ("部分", "partial"),
    ("唯一", "unique"),
    ("多个", "multiple"),
    ("单个", "single"),
    ("相同", "same"),
    ("不同", "different"),
    ("其他", "other"),
    ("相关", "related"),
    ("关键", "key"),
    ("主要", "main"),
    ("次要", "secondary"),
    ("直接", "direct"),
    ("间接", "indirect"),
    ("上游", "upstream"),
    ("下游", "downstream"),
    ("前序", "previous"),
    ("后续", "subsequent"),
    ("之前", "before"),
    ("之后", "after"),
    ("期间", "during"),
    ("当时", "at that time"),
    ("当前", "current"),
    ("历史", "historical"),
    ("未来", "future"),
    ("现有", "existing"),
    ("已有", "already have"),
    ("新的", "new"),
    ("旧的", "old"),
    ("第一", "first"),
    ("第二", "second"),
    ("第三", "third"),
    ("最后", "last"),
    ("初始", "initial"),
    ("最终", "final"),
    ("开始", "start"),
    ("结束", "end"),
    ("继续", "continue"),
    ("停止", "stop"),
    ("执行", "execute"),
    ("运行", "run"),
    ("处理", "process"),
    ("操作", "operate"),
    ("计算", "calculate"),
    ("统计", "statistics"),
    ("比较", "compare"),
    ("匹配", "match"),
    ("筛选", "filter"),
    ("排序", "sort"),
    ("分组", "group"),
    ("聚合", "aggregate"),
    ("去重", "deduplicate"),
    ("合并", "merge"),
    ("拆分", "split"),
    ("提取", "extract"),
    ("转换", "transform"),
    ("映射", "map"),
    ("关联", "associate"),
    ("连接", "connect"),
    ("断开", "disconnect"),
    ("包含", "contains"),
    ("不包含", "not contains"),
    ("等于", "equals"),
    ("不等于", "not equals"),
    ("大于", "greater than"),
    ("小于", "less than"),
    ("大于等于", "greater than or equal"),
    ("小于等于", "less than or equal"),
    ("在...之间", "between"),
    ("属于", "belongs to"),
    ("不属于", "not belongs to"),
    ("存在", "exists"),
    ("不存在", "not exists"),
    ("为空", "is empty"),
    ("非空", "is not empty"),
    ("是", "is"),
    ("否", "no"),
    ("真", "true"),
    ("假", "false"),
    ("和", "and"),
    ("或", "or"),
    ("非", "not"),
    ("与", "and"),
    ("的", "of"),
    ("了", ""),
    ("着", ""),
    ("过", ""),
    ("被", "by"),
    ("把", ""),
    ("将", "will"),
    ("对", "to"),
    ("从", "from"),
    ("向", "to"),
    ("为", "for"),
    ("给", "to"),
    ("在", "in"),
    ("于", "at"),
    ("以", "by"),
    ("及", "and"),
    ("以及", "and"),
    ("或", "or"),
    ("或者", "or"),
    ("但", "but"),
    ("但是", "but"),
    ("而", "and"),
    ("而且", "and"),
    ("并", "and"),
    ("并且", "and"),
    ("若", "if"),
    ("如果", "if"),
    ("则", "then"),
    ("那么", "then"),
    ("当", "when"),
    ("时", "when"),
    ("后", "after"),
    ("然后", "then"),
    ("因为", "because"),
    ("所以", "therefore"),
    ("因此", "therefore"),
    ("由于", "due to"),
    ("根据", "according to"),
    ("按照", "according to"),
    ("依据", "based on"),
    ("基于", "based on"),
    ("通过", "through"),
    ("经过", "through"),
    ("利用", "using"),
    ("使用", "use"),
    ("采用", "adopt"),
    ("应用", "apply"),
    ("用于", "used for"),
    ("作用", "role"),
    ("目的", "purpose"),
    ("目标", "target"),
    ("对象", "object"),
    ("结果", "result"),
    ("效果", "effect"),
    ("影响", "impact"),
    ("原因", "reason"),
    ("理由", "reason"),
    ("因素", "factor"),
    ("条件", "condition"),
    ("假设", "hypothesis"),
    ("结论", "conclusion"),
    ("决定", "decision"),
    ("判断", "judgment"),
    ("评价", "evaluation"),
    ("评估", "assessment"),
    ("分析", "analysis"),
    ("解析", "parse"),
    ("解释", "explanation"),
    ("说明", "description"),
    ("定义", "definition"),
    ("声明", "declaration"),
    ("规范", "specification"),
    ("规则", "rule"),
    ("标准", "standard"),
    ("要求", "requirement"),
    ("需求", "requirement"),
    ("期望", "expectation"),
    ("实际", "actual"),
    ("预期", "expected"),
    ("计划", "plan"),
    ("方案", "plan"),
    ("策略", "strategy"),
    ("方法", "method"),
    ("方式", "way"),
    ("模式", "mode"),
    ("模型", "model"),
    ("模块", "module"),
    ("组件", "component"),
    ("部件", "part"),
    ("元素", "element"),
    ("因子", "factor"),
    ("参数", "parameter"),
    ("变量", "variable"),
    ("常量", "constant"),
    ("属性", "attribute"),
    ("特性", "feature"),
    ("特征", "characteristic"),
    ("标识", "identifier"),
    ("标记", "mark"),
    ("标签", "label"),
    ("注释", "comment"),
    ("备注", "note"),
    ("信息", "information"),
    ("消息", "message"),
    ("通知", "notification"),
    ("警告", "warning"),
    ("错误", "error"),
    ("异常", "exception"),
    ("问题", "problem"),
    ("缺陷", "defect"),
    ("漏洞", "vulnerability"),
    ("风险", "risk"),
    ("威胁", "threat"),
    ("攻击", "attack"),
    ("防护", "protection"),
    ("安全", "security"),
    ("隐私", "privacy"),
    ("权限", "permission"),
    ("授权", "authorization"),
    ("认证", "authentication"),
    ("验证", "verification"),
    ("确认", "confirmation"),
    ("批准", "approval"),
    ("拒绝", "rejection"),
    ("允许", "allow"),
    ("禁止", "prohibit"),
    ("限制", "restriction"),
    ("约束", "constraint"),
    ("控制", "control"),
    ("管理", "management"),
    ("监控", "monitoring"),
    ("监督", "supervision"),
    ("审计", "audit"),
    ("检查", "inspection"),
    ("检测", "detection"),
    ("测试", "test"),
    ("调试", "debug"),
    ("诊断", "diagnosis"),
    ("修复", "repair"),
    ("恢复", "recovery"),
    ("备份", "backup"),
    ("还原", "restore"),
    ("同步", "synchronization"),
    ("更新", "update"),
    ("升级", "upgrade"),
    ("降级", "downgrade"),
    ("安装", "install"),
    ("卸载", "uninstall"),
    ("部署", "deploy"),
    ("发布", "release"),
    ("上线", "go live"),
    ("下线", "go offline"),
    ("启动", "start"),
    ("停止", "stop"),
    ("重启", "restart"),
    ("关闭", "close"),
    ("打开", "open"),
    ("创建", "create"),
    ("删除", "delete"),
    ("修改", "modify"),
    ("编辑", "edit"),
    ("保存", "save"),
    ("加载", "load"),
    ("读取", "read"),
    ("写入", "write"),
    ("导入", "import"),
    ("导出", "export"),
    ("上传", "upload"),
    ("下载", "download"),
    ("发送", "send"),
    ("接收", "receive"),
    ("请求", "request"),
    ("响应", "response"),
    ("调用", "call"),
    ("回调", "callback"),
    ("触发", "trigger"),
    ("监听", "listen"),
    ("订阅", "subscribe"),
    ("取消订阅", "unsubscribe"),
    ("发布", "publish"),
    ("推送", "push"),
    ("拉取", "pull"),
    ("获取", "get"),
    ("设置", "set"),
    ("添加", "add"),
    ("移除", "remove"),
    ("插入", "insert"),
    ("更新", "update"),
    ("替换", "replace"),
    ("交换", "swap"),
    ("复制", "copy"),
    ("粘贴", "paste"),
    ("剪切", "cut"),
    ("清除", "clear"),
    ("重置", "reset"),
    ("初始化", "initialize"),
    ("配置", "configure"),
    ("设置", "settings"),
    ("选项", "options"),
    ("参数", "parameters"),
    ("首选项", "preferences"),
    ("默认", "default"),
    ("自定义", "custom"),
    ("自动", "automatic"),
    ("手动", "manual"),
    ("批量", "batch"),
    ("单个", "single"),
    ("多个", "multiple"),
    ("全部", "all"),
    ("部分", "partial"),
    ("本地", "local"),
    ("远程", "remote"),
    ("内部", "internal"),
    ("外部", "external"),
    ("公共", "public"),
    ("私有", "private"),
    ("共享", "shared"),
    ("独立", "independent"),
    ("联合", "joint"),
    ("集中", "centralized"),
    ("分布", "distributed"),
    ("并行", "parallel"),
    ("串行", "serial"),
    ("同步", "synchronous"),
    ("异步", "asynchronous"),
    ("实时", "real-time"),
    ("离线", "offline"),
    ("在线", "online"),
    ("动态", "dynamic"),
    ("静态", "static"),
    ("临时", "temporary"),
    ("永久", "permanent"),
    ("长期", "long-term"),
    ("短期", "short-term"),
    ("定期", "periodic"),
    ("周期", "cycle"),
    ("频率", "frequency"),
    ("速率", "rate"),
    ("速度", "speed"),
    ("延迟", "delay"),
    ("超时", "timeout"),
    ("间隔", "interval"),
    ("持续时间", "duration"),
    ("时间戳", "timestamp"),
    ("日期", "date"),
    ("时间", "time"),
    ("时刻", "moment"),
    ("时段", "time period"),
    ("阶段", "stage"),
    ("步骤", "step"),
    ("流程", "process"),
    ("工序", "operation"),
    ("顺序", "sequence"),
    ("排序", "order"),
    ("优先级", "priority"),
    ("权重", "weight"),
    ("等级", "level"),
    ("层次", "layer"),
    ("维度", "dimension"),
    ("角度", "angle"),
    ("方面", "aspect"),
    ("范围", "scope"),
    ("领域", "domain"),
    ("区域", "area"),
    ("区间", "interval"),
    ("边界", "boundary"),
    ("限制", "limit"),
    ("阈值", "threshold"),
    ("基准", "baseline"),
    ("参考", "reference"),
    ("标准", "standard"),
    ("规范", "norm"),
    ("规则", "rule"),
    ("定律", "law"),
    ("原理", "principle"),
    ("定理", "theorem"),
    ("公式", "formula"),
    ("算法", "algorithm"),
    ("逻辑", "logic"),
    ("推理", "reasoning"),
    ("归纳", "induction"),
    ("演绎", "deduction"),
    ("统计", "statistics"),
    ("概率", "probability"),
    ("随机", "random"),
    ("采样", "sampling"),
    ("样本", "sample"),
    ("总体", "population"),
    ("分布", "distribution"),
    ("均值", "mean"),
    ("方差", "variance"),
    ("标准差", "standard deviation"),
    ("中位数", "median"),
    ("众数", "mode"),
    ("最大值", "maximum"),
    ("最小值", "minimum"),
    ("总和", "sum"),
    ("平均值", "average"),
    ("比率", "ratio"),
    ("比例", "proportion"),
    ("百分比", "percentage"),
    ("百分点", "percentage point"),
    ("基数", "base"),
    ("系数", "coefficient"),
    ("指数", "index"),
    ("指标", "indicator"),
    ("度量", "measure"),
    ("单位", "unit"),
    ("量纲", "dimension"),
    ("规模", "scale"),
    ("范围", "range"),
    ("程度", "degree"),
    ("水平", "level"),
    ("质量", "quality"),
    ("数量", "quantity"),
    ("总量", "total"),
    ("增量", "increment"),
    ("减量", "decrement"),
    ("变化", "change"),
    ("变化量", "change amount"),
    ("变化率", "change rate"),
    ("增长", "growth"),
    ("下降", "decline"),
    ("上升", "rise"),
    ("波动", "fluctuation"),
    ("趋势", "trend"),
    ("模式", "pattern"),
    ("规律", "law"),
    ("关联", "correlation"),
    ("因果", "causality"),
    ("影响", "influence"),
    ("作用", "effect"),
    ("功能", "function"),
    ("性能", "performance"),
    ("效率", "efficiency"),
    ("效果", "effectiveness"),
    ("效益", "benefit"),
    ("收益", "gain"),
    ("成本", "cost"),
    ("开销", "overhead"),
    ("资源", "resource"),
    ("资产", "asset"),
    ("负载", "load"),
    ("压力", "pressure"),
    ("容量", "capacity"),
    ("能力", "capability"),
    ("潜力", "potential"),
    ("优势", "advantage"),
    ("劣势", "disadvantage"),
    ("机会", "opportunity"),
    ("挑战", "challenge"),
    ("风险", "risk"),
    ("问题", "issue"),
    ("障碍", "obstacle"),
    ("困难", "difficulty"),
    ("解决方案", "solution"),
    ("措施", "measure"),
    ("对策", "countermeasure"),
    ("预防", "prevention"),
    ("保护", "protection"),
    ("防御", "defense"),
    ("应对", "response"),
    ("处理", "handling"),
    ("处置", "disposal"),
    ("管理", "management"),
    ("治理", "governance"),
    ("监管", "regulation"),
    ("监督", "supervision"),
    ("控制", "control"),
    ("调节", "regulation"),
    ("调整", "adjustment"),
    ("优化", "optimization"),
    ("改进", "improvement"),
    ("提升", "enhancement"),
    ("增强", "strengthening"),
    ("减弱", "weakening"),
    ("消除", "elimination"),
    ("减少", "reduction"),
    ("增加", "increase"),
    ("扩大", "expansion"),
    ("缩小", "contraction"),
    ("合并", "merger"),
    ("拆分", "splitting"),
    ("整合", "integration"),
    ("协调", "coordination"),
    ("协作", "collaboration"),
    ("合作", "cooperation"),
    ("竞争", "competition"),
    ("冲突", "conflict"),
    ("矛盾", "contradiction"),
    ("差异", "difference"),
    ("相似", "similarity"),
    ("相同", "sameness"),
    ("不同", "difference"),
    ("一致", "consistent"),
    ("不一致", "inconsistent"),
    ("匹配", "matching"),
    ("不匹配", "mismatching"),
    ("兼容", "compatible"),
    ("不兼容", "incompatible"),
    ("适用", "applicable"),
    ("不适用", "not applicable"),
    ("有效", "valid"),
    ("无效", "invalid"),
    ("正确", "correct"),
    ("错误", "incorrect"),
    ("准确", "accurate"),
    ("不准确", "inaccurate"),
    ("精确", "precise"),
    ("模糊", "fuzzy"),
    ("清晰", "clear"),
    ("明确", "explicit"),
    ("隐含", "implicit"),
    ("直接", "direct"),
    ("间接", "indirect"),
    ("简单", "simple"),
    ("复杂", "complex"),
    ("容易", "easy"),
    ("困难", "difficult"),
    ("可能", "possible"),
    ("不可能", "impossible"),
    ("肯定", "certain"),
    ("否定", "negative"),
    ("确定", "determined"),
    ("不确定", "undetermined"),
    ("已知", "known"),
    ("未知", "unknown"),
    ("可见", "visible"),
    ("不可见", "invisible"),
    ("公开", "public"),
    ("秘密", "secret"),
    ("机密", "confidential"),
    ("绝密", "top secret"),
    ("敏感", "sensitive"),
    ("关键", "critical"),
    ("重要", "important"),
    ("次要", "minor"),
    ("主要", "main"),
    ("核心", "core"),
    ("边缘", "edge"),
    ("中心", "center"),
    ("周围", "surrounding"),
    ("内部", "inside"),
    ("外部", "outside"),
    ("上层", "upper"),
    ("下层", "lower"),
    ("高层", "high-level"),
    ("底层", "low-level"),
    ("前端", "front-end"),
    ("后端", "back-end"),
    ("上游", "upstream"),
    ("下游", "downstream"),
    ("入口", "entry"),
    ("出口", "exit"),
    ("输入", "input"),
    ("输出", "output"),
    ("起点", "starting point"),
    ("终点", "ending point"),
    ("来源", "source"),
    ("去向", "destination"),
    ("原因", "cause"),
    ("结果", "result"),
    ("前提", "premise"),
    ("条件", "condition"),
    ("假设", "assumption"),
    ("结论", "conclusion"),
    ("推论", "inference"),
    ("预测", "prediction"),
    ("预报", "forecast"),
    ("预警", "early warning"),
    ("提示", "prompt"),
    ("建议", "suggestion"),
    ("推荐", "recommendation"),
    ("要求", "requirement"),
    ("需求", "need"),
    ("期望", "expectation"),
    ("目标", "goal"),
    ("目的", "objective"),
    ("意图", "intention"),
    ("计划", "plan"),
    ("安排", "arrangement"),
    ("部署", "deployment"),
    ("配置", "configuration"),
    ("设置", "setting"),
    ("参数", "parameter"),
    ("选项", "option"),
    ("选择", "choice"),
    ("决定", "decision"),
    ("判断", "judgment"),
    ("评估", "evaluation"),
    ("评价", "assessment"),
    ("考核", "assessment"),
    ("审查", "review"),
    ("审核", "audit"),
    ("检查", "check"),
    ("检验", "inspection"),
    ("验证", "validation"),
    ("确认", "confirmation"),
    ("认可", "recognition"),
    ("批准", "approval"),
    ("同意", "agreement"),
    ("拒绝", "refusal"),
    ("反对", "opposition"),
    ("支持", "support"),
    ("赞成", "approval"),
    ("许可", "permission"),
    ("授权", "authorization"),
    ("委托", "delegation"),
    ("代理", "proxy"),
    ("代表", "representative"),
    ("角色", "role"),
    ("职责", "responsibility"),
    ("责任", "liability"),
    ("义务", "obligation"),
    ("权利", "right"),
    ("利益", "interest"),
    ("权益", "rights and interests"),
    ("损失", "loss"),
    ("损害", "damage"),
    ("伤害", "harm"),
    ("保护", "protection"),
    ("维护", "maintenance"),
    ("保障", "guarantee"),
    ("确保", "ensure"),
    ("保证", "guarantee"),
    ("承诺", "commitment"),
    ("约定", "agreement"),
    ("规定", "regulation"),
    ("规则", "rule"),
    ("制度", "system"),
    ("机制", "mechanism"),
    ("体制", "structure"),
    ("体系", "system"),
    ("架构", "architecture"),
    ("结构", "structure"),
    ("组织", "organization"),
    ("机构", "institution"),
    ("部门", "department"),
    ("团队", "team"),
    ("小组", "group"),
    ("个人", "individual"),
    ("集体", "collective"),
    ("公众", "public"),
    ("社会", "society"),
    ("国家", "country"),
    ("政府", "government"),
    ("企业", "enterprise"),
    ("公司", "company"),
    ("组织", "organization"),
    ("机构", "institution"),
    ("单位", "unit"),
    ("部门", "department"),
    ("岗位", "position"),
    ("职位", "job title"),
    ("职务", "duty"),
    ("职称", "professional title"),
    ("级别", "level"),
    ("等级", "grade"),
    ("层次", "hierarchy"),
    ("阶段", "phase"),
    ("时期", "period"),
    ("时代", "era"),
    ("年度", "year"),
    ("季度", "quarter"),
    ("月份", "month"),
    ("日期", "date"),
    ("时间", "time"),
    ("时刻", "moment"),
    ("时分秒", "hour minute second"),
    ("毫秒", "millisecond"),
    ("微秒", "microsecond"),
    ("纳秒", "nanosecond"),
    ("秒", "second"),
    ("分钟", "minute"),
    ("小时", "hour"),
    ("天", "day"),
    ("周", "week"),
    ("月", "month"),
    ("年", "year"),
    ("今", "today"),
    ("昨", "yesterday"),
    ("明", "tomorrow"),
    ("前", "before"),
    ("后", "after"),
    ("上", "last"),
    ("下", "next"),
    ("初", "early"),
    ("末", "late"),
    ("始", "start"),
    ("终", "end"),
    ("起", "from"),
    ("止", "to"),
    ("内", "inside"),
    ("外", "outside"),
    ("中", "in"),
    ("间", "between"),
    ("旁", "beside"),
    ("侧", "side"),
    ("方", "direction"),
    ("面", "side"),
    ("头", "head"),
    ("尾", "tail"),
    ("首", "first"),
    ("末", "last"),
    ("前", "front"),
    ("后", "back"),
    ("左", "left"),
    ("右", "right"),
    ("东", "east"),
    ("西", "west"),
    ("南", "south"),
    ("北", "north"),
    ("上", "up"),
    ("下", "down"),
    ("高", "high"),
    ("低", "low"),
    ("大", "large"),
    ("小", "small"),
    ("多", "many"),
    ("少", "few"),
    ("长", "long"),
    ("短", "short"),
    ("宽", "wide"),
    ("窄", "narrow"),
    ("厚", "thick"),
    ("薄", "thin"),
    ("深", "deep"),
    ("浅", "shallow"),
    ("远", "far"),
    ("近", "near"),
    ("快", "fast"),
    ("慢", "slow"),
    ("早", "early"),
    ("晚", "late"),
    ("新", "new"),
    ("旧", "old"),
    ("好", "good"),
    ("坏", "bad"),
    ("优", "excellent"),
    ("劣", "inferior"),
    ("强", "strong"),
    ("弱", "weak"),
    ("硬", "hard"),
    ("软", "soft"),
    ("轻", "light"),
    ("重", "heavy"),
    ("热", "hot"),
    ("冷", "cold"),
    ("暖", "warm"),
    ("凉", "cool"),
    ("干", "dry"),
    ("湿", "wet"),
    ("满", "full"),
    ("空", "empty"),
    ("整", "whole"),
    ("零", "zero"),
    ("一", "one"),
    ("二", "two"),
    ("三", "three"),
    ("四", "four"),
    ("五", "five"),
    ("六", "six"),
    ("七", "seven"),
    ("八", "eight"),
    ("九", "nine"),
    ("十", "ten"),
    ("百", "hundred"),
    ("千", "thousand"),
    ("万", "ten thousand"),
    ("亿", "hundred million"),
    ("个", ""),
    ("第", "No."),
    ("每", "every"),
    ("各", "each"),
    ("某", "some"),
    ("该", "this"),
    ("此", "this"),
    ("那", "that"),
    ("哪", "which"),
    ("什", "what"),
    ("么", ""),
    ("怎", "how"),
    ("谁", "who"),
    ("何", "what"),
    ("几", "several"),
    ("些", "some"),
    ("等", "etc."),
]

def translate_text(text):
    if not isinstance(text, str):
        return text
    # Apply phrase replacements first (longest first)
    for cn, en in REPLACEMENTS:
        text = text.replace(cn, en)
    # Apply word replacements
    for cn, en in WORD_REPLACEMENTS:
        text = text.replace(cn, en)
    return text

def translate_object(obj):
    if isinstance(obj, dict):
        return {translate_text(k): translate_object(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [translate_object(v) for v in obj]
    elif isinstance(obj, str):
        return translate_text(obj)
    return obj

def has_chinese(text):
    if not isinstance(text, str):
        return False
    return bool(re.search(r'[一-鿿]', text))

# Process all files
all_files = []
for root, dirs, files in os.walk(SESSION_DIR):
    for f in files:
        all_files.append(os.path.join(root, f))

print(f"Total files: {len(all_files)}")
modified_count = 0
error_count = 0

for filepath in all_files:
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        # Check if content has Chinese
        if not has_chinese(content):
            continue

        # Try JSON
        try:
            data = json.loads(content)
            translated = translate_object(data)
            new_content = json.dumps(translated, ensure_ascii=False, indent=2)
        except json.JSONDecodeError:
            # Plain text replacement
            new_content = translate_text(content)

        if new_content != content:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(new_content)
            modified_count += 1
            print(f"Modified: {os.path.relpath(filepath, SESSION_DIR)}")
    except Exception as e:
        error_count += 1
        print(f"Error processing {filepath}: {e}")

print(f"\nDone. Modified: {modified_count}, Errors: {error_count}")
